{% set name = "hatch-min-requirements" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hatch_min_requirements-{{ version }}.tar.gz
  sha256: 45875bb8fe662b30f29b8bb1d98e2ef33de2c40e42c79a80c9ab0ef5160f6b27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - hatchling >=0.21.0

test:
  imports:
    - hatch_min_requirements
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tlambert03/hatch-min-requirements
  summary: Hatchling plugin to create optional-dependencies pinned to minimum versions
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dcherian
    - tlambert03
